### ISSUE TITLE
client.Proxy.callRemote() causes Content-Length to be set twice

### ISSUE THREAD

**Issue by ldanielburr** [tmoravec/fastjsonrpc#10]
The Request object used by twisted.web.client.Agent automatically sets the Content-Length header, so adding a Content-Length header in Proxy.callRemote will cause some HTTP servers to reject the message, as having 2 Content-Length values is not proper HTTP.

**Comment by ldanielburr** [comment]
Apologies for the erroneous report, I see the issue is already fixed in master, but the version currently available on pypi still has this bug.

**Comment by tmoravec** [comment]
Oh, yeah, I'll try to update pypi asap (well, tomorrow hopefully but no promises). In the meantime, you can just delete the line.

**Comment by ldanielburr** [comment]
Yes, that's what I did, and things work as expected, thanks.

**Comment by tmoravec** [comment]
Updated on PyPI, version bump to 0.3.0. Let me know if you run into any issues, I'll try to solve it ASAP.
Thank you for the report!
