### ISSUE TITLE
Can´t start example code

### ISSUE THREAD

**Issue by ghost** [tmoravec/fastjsonrpc#11]
Hi,

im sorry for this maybe stupid question but when i try to run the example code for examples/ssl_server.tac the program finished after maybe 2 seconds. no output, no errors. i replaced the cert & key file with my own.

Do you have any idea ?

**Comment by tmoravec** [comment]
Hi,

I've just tried it with Twisted 13.2.0 and 14.0.0 and in both cases it works. Remember that if you run twistd without the -n argument, it will run in the background, so it "looks" like it ended after a few moments.

I run it like this:
In console 1: twistd -n -y ssl-server.tac
In console 2: python ssl-client.py

Just tested it on OS X Mavericks and Centos 7.

**Comment by ghost** [comment]
Thanks, perfect. Now it´s working.
But i have another question: Is it possible to merge the two scripts ssl-server and auth-server to get an ssl secured server with authentication ?

**Comment by tmoravec** [comment]
Of course. You'd do something like this:
Server: https://gist.github.com/tadeas/1affe6efe7b3b94d7910
Client: https://gist.github.com/tadeas/90c5cbc52fc505c87b3b

**Comment by ghost** [comment]
Wohoo ;) awsome ! Many Thanks.

One last question: Can twisted handle base64 credentials ? i have an application which sends the credentials base64 encoded and i got a 401 - Unauthorized error. I don´t know where i have to place the function which decode the base64 string before twisted check the credentials against the httpd.password

Again, many thanks for your help ;)

**Comment by tmoravec** [comment]
Basic authentication, the one fastjsonrpc supports, is (well, should be at least) base64. If I run the example auth-server and auth-client, I can see the Auhtorization: Basic header, including base64 encrypted credentials in tcpdump. 

Do you have some example request that doesn't work? I'm interested in the HTTP headers, not the request content itself.

**Comment by ghost** [comment]
Ok shame on me. Everything is fine. I missed some characters to paste in the password file.
Thank you very much for your help and your great work :)
